# StealthDNS base config
# field with (-) does not support dynamic update

# UpstreamDNS (-): upstream DNS server. Parse non-NHP related DNS requests and domain names returned by the nhp-server.
# SetSystemDNS (-): automatically configure system DNS. Requires administrator rights and SetSystemDNS to be true. Otherwise, manually set the primary DNS to 127.0.0.1.
# RemoveLocalDNS (-): Remove local DNS proxy. Deletes the 127.0.0.1 DNS proxy after it is set, if RemoveLocalDNS is true.
# LogLevel: 0: silent, 1: error, 2: info, 3: audit, 4: debug, 5: trace.
UpstreamDNS = "8.8.8.8"
SetSystemDNS = true
RemoveLocalDNS = true
LogLevel = 4